---

name: CI

"on": [push, pull_request]

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - run: yamllint com.github.rkoesters.xkcd-gtk.yaml
      - run: yamllint .github/workflows/*.yml
