---

name: CI

"on": [push, pull_request]

jobs:
  flatpak-builder:
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged

    steps:
      - uses: actions/checkout@v2

    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        manifest-path: com.github.rkoesters.xkcd-gtk.yaml
